---
Title: 'Pytorchのエラー「PyTorch: RuntimeError: device >= 0 && device < num_gpus INTERNAL
  ASSERT FAILED」'
Category:
- Python
- 備忘録
- Pytorch
Date: 2024-07-12T18:56:03+09:00
URL: https://fallpoke-tech.hatenadiary.jp/entry/2024/07/12/185603
EditURL: https://blog.hatena.ne.jp/fallpoke/fallpoke-tech.hatenadiary.jp/atom/entry/6801883189121386799
---

<p>お疲れ様です。</p>
<p> </p>
<p>Pytorch使用時に発生したエラーの対処についての備忘録です。</p>
<p>基本的には調べたサイトや記事をまとめただけになります。</p>
<p> </p>
<ul>
<li>エラー文</li>
</ul>
<p><strong>PyTorch: RuntimeError: device &gt;= 0 &amp;&amp; device &lt; num_gpus INTERNAL ASSERT FAILED</strong></p>
<p> </p>
<p>公式GitHubのissueでも議論されている内容ですね。</p>
<p><iframe src="https://hatenablog-parts.com/embed?url=https%3A%2F%2Fgithub.com%2Fpytorch%2Fpytorch%2Fpull%2F122815" title="Don't cache device_count if we haven't initialized CUDA yet by ezyang · Pull Request #122815 · pytorch/pytorch" class="embed-card embed-webcard" scrolling="no" frameborder="0" style="display: block; width: 100%; height: 155px; max-width: 500px; margin: 10px 0px;" loading="lazy"></iframe><cite class="hatena-citation"><a href="https://github.com/pytorch/pytorch/pull/122815">github.com</a></cite></p>
<p><iframe src="https://hatenablog-parts.com/embed?url=https%3A%2F%2Fgithub.com%2Fpytorch%2Fpytorch%2Fissues%2F126344" title="PyTorch: RuntimeError: device &gt;= 0 &amp;&amp; device &lt; num_gpus INTERNAL ASSERT FAILED · Issue #126344 · pytorch/pytorch" class="embed-card embed-webcard" scrolling="no" frameborder="0" style="display: block; width: 100%; height: 155px; max-width: 500px; margin: 10px 0px;" loading="lazy"></iframe><cite class="hatena-citation"><a href="https://github.com/pytorch/pytorch/issues/126344">github.com</a></cite></p>
<p> </p>
<ul>
<li>対処方法</li>
</ul>
<p>1．</p>
<p>下記のコードを記載する。</p>
<pre><code>
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["WORLD_SIZE"] = "1"
import torch
  </code></pre>
<p>pytorchをimportする前にosモジュールで環境変数<br /><code>"CUDA_VISIBLE_DEVICES</code>"と"<code>WORLD_SIZE</code>"を指定するように書く。</p>
<p>私の場合はこれでエラーは解消しました。</p>
<p> </p>
<p>2．</p>
<p>1の方法で解消しない場合もあるようで、その場合の代替案みたいなものが以下のサイトにあります。</p>
<p>Pytorch自体のバグなので、ライブラリのソースから書き換えてしまおうという感じですね。（個人的にはあまりやりたくはないですが…。）</p>
<p><iframe src="https://hatenablog-parts.com/embed?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F78486965%2Fpytorch-runtimeerror-device-0-device-num-gpus-internal-assert-failed" title="PyTorch RuntimeError: device &gt;= 0 &amp;&amp; device &lt; num_gpus INTERNAL ASSERT FAILED" class="embed-card embed-webcard" scrolling="no" frameborder="0" style="display: block; width: 100%; height: 155px; max-width: 500px; margin: 10px 0px;" loading="lazy"></iframe><cite class="hatena-citation"><a href="https://stackoverflow.com/questions/78486965/pytorch-runtimeerror-device-0-device-num-gpus-internal-assert-failed">stackoverflow.com</a></cite></p>
<p> </p>
<p>3．</p>
<p>そもそもPytorchのバージョンを変えてしまえば解消することがほとんどではないでしょうか。</p>
<p>基本的に最近（2024年7月あたり）のバージョンで起こることが多いみたいです。</p>
<p>私の場合もPytorch2.3.0を使用している際に起こりました。ただ、いつも使っているそれ以外のバージョンのPytorchでは一度も起こったことがないんですよね…。</p>
<p>今回の場合はバージョンを変えられない状況での開発だったので1の方法になりました。</p>
<p> </p>
<ul>
<li>補足</li>
</ul>
<p>最後に今回エラーが発生した環境を簡単に記載しておきます。</p>
<p>ちなみに後からWindows環境で同じライブラリバージョンをインストールして試してみたものの、エラーの再現はできませんでした。</p>
<p>（何か足りないものがあるかもですが…。）</p>
<blockquote>
<p>OS: Linux</p>
<p>Pytorch: 2.3.0</p>
<p>CUDA: 12.1</p>
</blockquote>
<p> </p>
